profile_desc_template = {
    "initiate": "initiate a fight",
    "big_ult": "cast a game changing ultimate",
    "offlane": "survive the hard lane and come out on top",
    "tank": "tank through all the damage there is",
    "heal": "provide healing for the team",
    "push": "push down towers with ease",
    "gank": "rotate to other lanes and gank effectively",
    "mobile": "slip through the enemies' fingers when being ganked"
}

profile_stats = {
    "initiate": "initiator",
    "big_ult": "big ultimate",
    "offlane": "offlaner",
    "tank": "tank",
    "heal": "healer",
    "push": "pusher",
    "gank": "ganker",
    "mobile": "escape/mobility"
}

profile_type_template = {
    "Right Click Carry": "The enemies can't cc you when they're dead from 3 right clicks",
    "General Damage Dealer": "Likes to delete heroes from the game",
    "Spell Caster/ Carry": "There's never a lack of burst damage when you're in the game",
    "Magical Damage/ Utility": "The more buttons you press in quick succession, the harder you win the game",
    "Hard Support": "The support life chose you, the most important (yet neglected) role in the game",
    "Spell Casting Support": "The support life chose you, that doesn't mean KS is not fun",
    "Well Rounded Player": "Either you're a master at every role, or you main the random button"
}

profile_type_bg = {
    "Right Click Carry": "images/dota_bg/right_click.jpg",
    "General Damage Dealer": "images/dota_bg/damage_dealer.jpg",
    "Spell Caster/ Carry": "images/dota_bg/magical_dmg.jpg",
    "Magical Damage/ Utility": "images/dota_bg/magic_utility.jpg",
    "Hard Support": "images/dota_bg/support.jpg",
    "Spell Casting Support": "images/dota_bg/semi_support.jpg",
    "Well Rounded Player": "images/dota_bg/all.jpg"
}

hero_stats = {
    1: {
        "localized_name": "Anti-Mage",
        "id": 1,
        "spell_caster": False,
        "right_clicker": True,
        "support": False,
        "initiate": 0,
        "big_ult": 0,
        "offlane": 0,
        "tank": 0,
        "heal": 0,
        "push": 4,
        "gank": 1,
        "mobile": 4

    },
    2: {
        "localized_name": "Axe",
        "id": 2,
        "spell_caster": False,
        "right_clicker": False,
        "support": False,
        "initiate": 5,
        "big_ult": 2,
        "offlane": 1,
        "tank": 5,
        "heal": 0,
        "push": 0,
        "gank": 4,
        "mobile": 0
    },
    3: {
        "localized_name": "Bane",
        "id": 3,
        "spell_caster": False,
        "right_clicker": False,
        "support": True,
        "initiate": 2,
        "big_ult": 3,
        "offlane": 1,
        "tank": 0,
        "heal": 0,
        "push": 0,
        "gank": 3,
        "mobile": 0
    },
    4: {
        "localized_name": "Bloodseeker",
        "id": 4,
        "spell_caster": False,
        "right_clicker": True,
        "support": False,
        "initiate": 1,
        "big_ult": 2,
        "offlane": 3,
        "tank": 0,
        "heal": 0,
        "push": 1,
        "gank": 3,
        "mobile": 0
    },
    5: {
        "localized_name": "Crystal Maiden",
        "id": 5,
        "spell_caster": True,
        "right_clicker": False,
        "support": True,
        "initiate": 2,
        "big_ult": 5,
        "offlane": 1,
        "tank": 0,
        "heal": 0,
        "push": 0,
        "gank": 4,
        "mobile": 0
    },
    6: {
        "localized_name": "Drow Ranger",
        "id": 6,
        "spell_caster": False,
        "right_clicker": True,
        "support": False,
        "initiate": 0,
        "big_ult": 0,
        "offlane": 2,
        "tank": 0,
        "heal": 0,
        "push": 0,
        "gank": 2,
        "mobile": 0
    },
    7: {
        "localized_name": "Earthshaker",
        "id": 7,
        "spell_caster": True,
        "right_clicker": False,
        "support": True,
        "initiate": 5,
        "big_ult": 5,
        "offlane": 3,
        "tank": 4,
        "heal": 0,
        "push": 1,
        "gank": 4,
        "mobile": 0
    },
    8: {
        "localized_name": "Juggernaut",
        "id": 8,
        "spell_caster": False,
        "right_clicker": True,
        "support": False,
        "initiate": 2,
        "big_ult": 3,
        "offlane": 1,
        "tank": 0,
        "heal": 2,
        "push": 1,
        "gank": 1,
        "mobile": 3
    },
    9: {
        "localized_name": "Mirana",
        "id": 9,
        "spell_caster": True,
        "right_clicker": False,
        "support": False,
        "initiate": 2,
        "big_ult": 4,
        "offlane": 4,
        "tank": 0,
        "heal": 0,
        "push": 1,
        "gank": 4,
        "mobile": 3
    },
    10: {
        "localized_name": "Shadow Fiend",
        "id": 11,
        "spell_caster": True,
        "right_clicker": True,
        "support": False,
        "initiate": 2,
        "tank": 0,
        "big_ult": 5,
        "offlane": 0,
        "heal": 0,
        "push": 2,
        "gank": 1,
        "mobile": 0
    },
    11: {
        "localized_name": "Morphling",
        "id": 10,
        "spell_caster": True,
        "right_clicker": True,
        "support": False,
        "initiate": 2,
        "big_ult": 3,
        "offlane": 1,
        "tank": 0,
        "heal": 0,
        "push": 1,
        "gank": 2,
        "mobile": 4
    },
    12: {
        "localized_name": "Phantom Lancer",
        "id": 12,
         "spell_caster": False,
        "right_clicker": True,
        "support": False,
        "initiate": 2,
        "big_ult": 0,
        "offlane": 1,
        "tank": 0,
        "heal": 0,
        "push": 5,
        "gank": 1,
        "mobile": 4
    },
    13: {
        "localized_name": "Puck",
        "id": 13,
        "spell_caster": True,
        "right_clicker": False,
        "support": False,
        "initiate": 5,
        "big_ult": 5,
        "offlane": 3,
        "tank": 0,
        "heal": 0,
        "push": 2,
        "gank": 4,
        "mobile": 5
    },
    14: {
        "localized_name": "Pudge",
        "id": 14,
        "spell_caster": False,
        "right_clicker": False,
        "support": False,
        "initiate": 3,
        "big_ult": 1,
        "offlane": 2,
        "tank": 4,
        "heal": 0,
        "push": 1,
        "gank": 5,
        "mobile": 0
    },
    15: {
        "localized_name": "Razor",
        "id": 15,
        "spell_caster": True,
        "right_clicker": False,
        "support": False,
        "initiate": 2,
        "big_ult": 3,
        "offlane": 2,
        "tank": 1,
        "heal": 0,
        "push": 4,
        "gank": 2,
        "mobile": 0
    },
    16: {
        "localized_name": "Sand King",
        "id": 16,
        "spell_caster": True,
        "right_clicker": False,
        "support": False,
        "initiate": 5,
        "big_ult": 5,
        "offlane": 1,
        "tank": 1,
        "heal": 0,
        "push": 1,
        "gank": 4,
        "mobile": 2
    },
    17: {
        "localized_name": "Storm Spirit",
        "id": 17,
        "spell_caster": True,
        "right_clicker": False,
        "support": False,
        "initiate": 5,
        "big_ult": 1,
        "offlane": 2,
        "tank": 0,
        "heal": 0,
        "push": 2,
        "gank": 5,
        "mobile": 5
    },
    18: {
        "localized_name": "Sven",
        "id": 18,
        "spell_caster": False,
        "right_clicker": True,
        "support": False,
        "initiate": 5,
        "big_ult": 0,
        "offlane": 0,
        "tank": 4,
        "heal": 0,
        "push": 2,
        "gank": 2,
        "mobile": 0
    },
    19: {
        "localized_name": "Tiny",
        "id": 19,
        "spell_caster": False,
        "right_clicker": True,
        "support": False,
        "initiate": 3,
        "big_ult": 2,
        "offlane": 1,
        "tank": 5,
        "heal": 0,
        "push": 5,
        "gank": 1,
        "mobile": 0
    },
    20: {
        "localized_name": "Vengeful Spirit",
        "id": 20,
        "spell_caster": False,
        "right_clicker": False,
        "support": True,
        "initiate": 5,
        "big_ult": 2,
        "offlane": 1,
        "tank": 0,
        "heal": 0,
        "push": 2,
        "gank": 5,
        "mobile": 2
    },
    21: {
        "localized_name": "Windranger",
        "id": 21,
        "spell_caster": False,
        "right_clicker": True,
        "support": True,
        "initiate": 3,
        "big_ult": 1,
        "offlane": 5,
        "tank": 0,
        "heal": 0,
        "push": 2,
        "gank": 4,
        "mobile": 3
    },
    22: {
        "localized_name": "Zeus",
        "id": 22,
        "spell_caster": True,
        "right_clicker": False,
        "support": False,
        "initiate": 0,
        "big_ult": 5,
        "offlane": 0,
        "tank": 0,
        "heal": 0,
        "push": 2,
        "gank": 3,
        "mobile": 0
    },
    23: {
        "localized_name": "Kunkka",
        "id": 23,
        "spell_caster": True,
        "right_clicker": True,
        "support": False,
        "initiate": 3,
        "big_ult": 5,
        "offlane": 2,
        "tank": 0,
        "heal": 0,
        "push": 3,
        "gank": 2,
        "mobile": 0
    },
    25: {
        "localized_name": "Lina",
        "id": 25,
        "spell_caster": True,
        "right_clicker": False,
        "support": True,
        "initiate": 2,
        "big_ult": 4,
        "offlane": 0,
        "tank": 0,
        "heal": 0,
        "push": 2,
        "gank": 2,
        "mobile": 0
    },
    31: {
        "localized_name": "Lich",
        "id": 31,
        "spell_caster": False,
        "right_clicker": False,
        "support": True,
        "initiate": 0,
        "big_ult": 5,
        "offlane": 1,
        "tank": 0,
        "heal": 0,
        "push": 1,
        "gank": 1,
        "mobile": 0
    },
    26: {
        "localized_name": "Lion",
        "id": 26,
        "spell_caster": False,
        "right_clicker": False,
        "support": True,
        "initiate": 3,
        "big_ult": 4,
        "offlane": 1,
        "tank": 0,
        "heal": 0,
        "push": 0,
        "gank": 4,
        "mobile": 0
    },
    27: {
        "localized_name": "Shadow Shaman",
        "id": 27,
        "spell_caster": False,
        "right_clicker": False,
        "support": True,
        "initiate": 0,
        "big_ult": 4,
        "offlane": 1,
        "tank": 0,
        "heal": 0,
        "push": 5,
        "gank": 3,
        "mobile": 0
    },
    28: {
        "localized_name": "Slardar",
        "id": 28,
        "spell_caster": False,
        "right_clicker": False,
        "support": False,
        "initiate": 5,
        "big_ult": 1,
        "offlane": 2,
        "tank": 4,
        "heal": 0,
        "push": 1,
        "gank": 5,
        "mobile": 1
    },
    29: {
        "localized_name": "Tidehunter",
        "id": 29,
        "spell_caster": False,
        "right_clicker": False,
        "support": True,
        "initiate": 4,
        "big_ult": 5,
        "offlane": 5,
        "tank": 4,
        "heal": 0,
        "push": 1,
        "gank": 2,
        "mobile": 0
    },
    30: {
        "localized_name": "Witch Doctor",
        "id": 30,
        "spell_caster": False,
        "right_clicker": False,
        "support": True,
        "initiate": 1,
        "big_ult": 5,
        "offlane": 1,
        "tank": 0,
        "heal": 5,
        "push": 0,
        "gank": 2,
        "mobile": 0
    },
    32: {
        "localized_name": "Riki",
        "id": 32,
        "spell_caster": False,
        "right_clicker": True,
        "support": False,
        "initiate": 0,
        "big_ult": 0,
        "offlane": 0,
        "tank": 0,
        "heal": 0,
        "push": 0,
        "gank": 5,
        "mobile": 4
    },
    33: {
        "localized_name": "Enigma",
        "id": 33,
        "spell_caster": True,
        "right_clicker": False,
        "support": True,
        "initiate": 5,
        "big_ult": 5,
        "offlane": 1,
        "tank": 0,
        "heal": 0,
        "push": 4,
        "gank": 2,
        "mobile": 0
    },
    34: {
        "localized_name": "Tinker",
        "id": 34,
        "spell_caster": True,
        "right_clicker": False,
        "support": False,
        "initiate": 0,
        "big_ult": 1,
        "offlane": 0,
        "tank": 0,
        "heal": 0,
        "push": 5,
        "gank": 4,
        "mobile": 0
    },
    35: {
        "localized_name": "Sniper",
        "id": 35,
        "spell_caster": False,
        "right_clicker": True,
        "support": False,
        "initiate": 0,
        "big_ult": 0,
        "offlane": 1,
        "tank": 0,
        "heal": 0,
        "push": 1,
        "gank": 0,
        "mobile": 0
    },
    36: {
        "localized_name": "Necrophos",
        "id": 36,
        "spell_caster": True,
        "right_clicker": False,
        "support": False,
        "initiate": 0,
        "big_ult": 4,
        "offlane": 1,
        "tank": 1,
        "heal": 0,
        "push": 5,
        "gank": 3,
        "mobile": 0
    },
    37: {
        "localized_name": "Warlock",
        "id": 37,
        "spell_caster": False,
        "right_clicker": False,
        "support": True,
        "initiate": 3,
        "big_ult": 5,
        "offlane": 2,
        "tank": 0,
        "heal": 3,
        "push": 4,
        "gank": 1,
        "mobile": 0
    },
    38: {
        "localized_name": "Beastmaster",
        "id": 38,
        "spell_caster": False,
        "right_clicker": False,
        "support": False,
        "initiate": 4,
        "big_ult": 5,
        "offlane": 5,
        "tank": 3,
        "heal": 0,
        "push": 4,
        "gank": 1,
        "mobile": 0
    },
    39: {
        "localized_name": "Queen of Pain",
        "id": 39,
        "spell_caster": True,
        "right_clicker": False,
        "support": False,
        "initiate": 4,
        "big_ult": 5,
        "offlane": 0,
        "tank": 0,
        "heal": 0,
        "push": 1,
        "gank": 5,
        "mobile": 4
    },
    40: {
        "localized_name": "Venomancer",
        "id": 40,
        "spell_caster": False,
        "right_clicker": False,
        "support": True,
        "initiate": 1,
        "big_ult": 5,
        "offlane": 3,
        "tank": 0,
        "heal": 0,
        "push": 4,
        "gank": 1,
        "mobile": 0
    },
    41: {
        "localized_name": "Faceless Void",
        "id": 41,
        "spell_caster": False,
        "right_clicker": True,
        "support": False,
        "initiate": 5,
        "big_ult": 5,
        "offlane": 3,
        "tank": 2,
        "heal": 0,
        "push": 1,
        "gank": 4,
        "mobile": 4
    },
    42: {
        "localized_name": "Wraith King",
        "id": 42,
        "spell_caster": False,
        "right_clicker": True,
        "support": False,
        "initiate": 4,
        "big_ult": 2,
        "offlane": 1,
        "tank": 5,
        "heal": 0,
        "push": 0,
        "gank": 2,
        "mobile": 0
    },
    43: {
        "localized_name": "Death Prophet",
        "id": 43,
        "spell_caster": True,
        "right_clicker": False,
        "support": False,
        "initiate": 0,
        "big_ult": 4,
        "offlane": 0,
        "tank": 1,
        "heal": 0,
        "push": 5,
        "gank": 0,
        "mobile": 0
    },
    44: {
        "localized_name": "Phantom Assassin",
        "id": 44,
        "spell_caster": False,
        "right_clicker": True,
        "support": False,
        "initiate": 0,
        "big_ult": 2,
        "offlane": 0,
        "tank": 0,
        "heal": 0,
        "push": 1,
        "gank": 3,
        "mobile": 2
    },
    45: {
        "localized_name": "Pugna",
        "id": 45,
        "spell_caster": True,
        "right_clicker": False,
        "support": True,
        "initiate": 0,
        "big_ult": 0,
        "offlane": 2,
        "tank": 0,
        "heal": 0,
        "push": 5,
        "gank": 1,
        "mobile": 0
    },
    46: {
        "localized_name": "Templar Assassin",
        "id": 46,
        "spell_caster": False,
        "right_clicker": True,
        "support": False,
        "initiate": 0,
        "big_ult": 0,
        "offlane": 0,
        "tank": 0,
        "heal": 0,
        "push": 0,
        "gank": 5,
        "mobile": 1
    },
    47: {
        "localized_name": "Viper",
        "id": 47,
        "spell_caster": False,
        "right_clicker": True,
        "support": False,
        "initiate": 0,
        "big_ult": 0,
        "offlane": 1,
        "tank": 2,
        "heal": 0,
        "push": 0,
        "gank": 0,
        "mobile": 0
    },
    48: {
        "localized_name": "Luna",
        "id": 48,
        "spell_caster": True,
        "right_clicker": True,
        "support": False,
        "initiate": 1,
        "big_ult": 5,
        "offlane": 0,
        "tank": 0,
        "heal": 0,
        "push": 5,
        "gank": 1,
        "mobile": 0
    },
    49: {
        "localized_name": "Dragon Knight",
        "id": 49,
        "spell_caster": False,
        "right_clicker": True,
        "support": False,
        "initiate": 4,
        "big_ult": 2,
        "offlane": 1,
        "tank": 4,
        "heal": 0,
        "push": 4,
        "gank": 2,
        "mobile": 0
    },
    50: {
        "localized_name": "Dazzle",
        "id": 50,
        "spell_caster": False,
        "right_clicker": False,
        "support": True,
        "initiate": 0,
        "big_ult": 3,
        "offlane": 0,
        "tank": 0,
        "heal": 5,
        "push": 0,
        "gank": 0,
        "mobile": 0
    },
    51: {
        "localized_name": "Clockwerk",
        "id": 51,
        "spell_caster": False,
        "right_clicker": False,
        "support": False,
        "initiate": 5,
        "big_ult": 1,
        "offlane": 5,
        "tank": 1,
        "heal": 0,
        "push": 0,
        "gank": 5,
        "mobile": 2
    },
    52: {
        "localized_name": "Leshrac",
        "id": 52,
        "spell_caster": True,
        "right_clicker": False,
        "support": False,
        "initiate": 1,
        "big_ult": 3,
        "offlane": 0,
        "tank": 0,
        "heal": 0,
        "push": 4,
        "gank": 2,
        "mobile": 0
    },
    53: {
        "localized_name": "Nature's Prophet",
        "id": 53,
        "spell_caster": False,
        "right_clicker": True,
        "support": False,
        "initiate": 1,
        "big_ult": 2,
        "offlane": 5,
        "tank": 0,
        "heal": 0,
        "push": 5,
        "gank": 4,
        "mobile": 2
    },
    54: {
        "localized_name": "Lifestealer",
        "id": 54,
        "spell_caster": False,
        "right_clicker": True,
        "support": False,
        "initiate": 0,
        "big_ult": 0,
        "offlane": 0,
        "tank": 4,
        "heal": 0,
        "push": 0,
        "gank": 0,
        "mobile": 1
    },
    55: {
        "localized_name": "Dark Seer",
        "id": 55,
        "spell_caster": True,
        "right_clicker": False,
        "support": True,
        "initiate": 3,
        "big_ult": 5,
        "offlane": 5,
        "tank": 1,
        "heal": 0,
        "push": 3,
        "gank": 2,
        "mobile": 2
    },
    56: {
        "localized_name": "Clinkz",
        "id": 56,
        "spell_caster": False,
        "right_clicker": True,
        "support": False,
        "initiate": 0,
        "big_ult": 0,
        "offlane": 5,
        "tank": 0,
        "heal": 0,
        "push": 1,
        "gank": 3,
        "mobile": 3
    },
    57: {
        "localized_name": "Omniknight",
        "id": 57,
        "spell_caster": True,
        "right_clicker": False,
        "support": True,
        "initiate": 0,
        "big_ult": 5,
        "offlane": 3,
        "tank": 3,
        "heal": 3,
        "push": 0,
        "gank": 0,
        "mobile": 0
    },
    58: {
        "localized_name": "Enchantress",
        "id": 58,
        "spell_caster": False,
        "right_clicker": False,
        "support": True,
        "initiate": 0,
        "big_ult": 1,
        "offlane": 1,
        "tank": 1,
        "heal": 2,
        "push": 3,
        "gank": 5,
        "mobile": 1
    },
    59: {
        "localized_name": "Huskar",
        "id": 59,
        "spell_caster": False,
        "right_clicker": True,
        "support": False,
        "initiate": 2,
        "big_ult": 1,
        "offlane": 1,
        "tank": 2,
        "heal": 1,
        "push": 0,
        "gank": 4,
        "mobile": 1
    },
    60: {
        "localized_name": "Night Stalker",
        "id": 60,
        "spell_caster": False,
        "right_clicker": False,
        "support": False,
        "initiate": 1,
        "big_ult": 2,
        "offlane": 3,
        "tank": 3,
        "heal": 0,
        "push": 0,
        "gank": 5,
        "mobile": 1
    },
    61: {
        "localized_name": "Broodmother",
        "id": 61,
        "spell_caster": False,
        "right_clicker": True,
        "support": False,
        "initiate": 1,
        "big_ult": 0,
        "offlane": 5,
        "tank": 1,
        "heal": 0,
        "push": 5,
        "gank": 2,
        "mobile": 3
    },
    62: {
        "localized_name": "Bounty Hunter",
        "id": 62,
        "spell_caster": False,
        "right_clicker": False,
        "support": True,
        "initiate": 1,
        "big_ult": 0,
        "offlane": 5,
        "tank": 0,
        "heal": 0,
        "push": 0,
        "gank": 5,
        "mobile": 4
    },
    63: {
        "localized_name": "Weaver",
        "id": 63,
        "spell_caster": False,
        "right_clicker": True,
        "support": False,
        "initiate": 0,
        "big_ult": 1,
        "offlane": 5,
        "tank": 0,
        "heal": 0,
        "push": 1,
        "gank": 3,
        "mobile": 4
    },
    64: {
        "localized_name": "Jakiro",
        "id": 64,
        "spell_caster": True,
        "right_clicker": False,
        "support": True,
        "initiate": 2,
        "big_ult": 3,
        "offlane": 1,
        "tank": 1,
        "heal": 0,
        "push": 3,
        "gank": 2,
        "mobile": 0
    },
    65: {
        "localized_name": "Batrider",
        "id": 65,
        "spell_caster": False,
        "right_clicker": False,
        "support": False,
        "initiate": 5,
        "big_ult": 3,
        "offlane": 4,
        "tank": 0,
        "heal": 0,
        "push": 2,
        "gank": 5,
        "mobile": 2
    },
    66: {
        "localized_name": "Chen",
        "id": 66,
        "spell_caster": False,
        "right_clicker": False,
        "support": True,
        "initiate": 0,
        "big_ult": 3,
        "offlane": 0,
        "tank": 0,
        "heal": 2,
        "push": 4,
        "gank": 4,
        "mobile": 0
    },
    67: {
        "localized_name": "Spectre",
        "id": 67,
        "spell_caster": False,
        "right_clicker": True,
        "support": False,
        "initiate": 3,
        "big_ult": 5,
        "offlane": 0,
        "tank": 0,
        "heal": 0,
        "push": 1,
        "gank": 3,
        "mobile": 1
    },
    69: {
        "localized_name": "Doom",
        "id": 69,
        "spell_caster": True,
        "right_clicker": False,
        "support": False,
        "initiate": 1,
        "big_ult": 5,
        "offlane": 2,
        "tank": 4,
        "heal": 0,
        "push": 0,
        "gank": 3,
        "mobile": 0
    },
    68: {
        "localized_name": "Ancient Apparition",
        "id": 68,
        "spell_caster": True,
        "right_clicker": False,
        "support": True,
        "initiate": 0,
        "big_ult": 5,
        "offlane": 0,
        "tank": 0,
        "heal": 0,
        "push": 1,
        "gank": 1,
        "mobile": 0
    },
    70: {
        "localized_name": "Ursa",
        "id": 70,
        "spell_caster": False,
        "right_clicker": True,
        "support": False,
        "initiate": 4,
        "big_ult": 0,
        "offlane": 0,
        "tank": 1,
        "heal": 0,
        "push": 0,
        "gank": 2,
        "mobile": 0
    },
    71: {
        "localized_name": "Spirit Breaker",
        "id": 71,
        "spell_caster": False,
        "right_clicker": False,
        "support": False,
        "initiate": 5,
        "big_ult": 0,
        "offlane": 2,
        "tank": 3,
        "heal": 0,
        "push": 0,
        "gank": 5,
        "mobile": 2
    },
    72: {
        "localized_name": "Gyrocopter",
        "id": 72,
        "spell_caster": False,
        "right_clicker": True,
        "support": False,
        "initiate": 0,
        "big_ult": 3,
        "offlane": 0,
        "tank": 0,
        "heal": 0,
        "push": 1,
        "gank": 1,
        "mobile": 0
    },
    73: {
        "localized_name": "Alchemist",
        "id": 73,
        "spell_caster": False,
        "right_clicker": True,
        "support": False,
        "initiate": 2,
        "big_ult": 1,
        "offlane": 1,
        "tank": 5,
        "heal": 0,
        "push": 2,
        "gank": 1,
        "mobile": 0
    },
    74: {
        "localized_name": "Invoker",
        "id": 74,
        "spell_caster": True,
        "right_clicker": False,
        "support": False,
        "initiate": 3,
        "big_ult": 5,
        "offlane": 0,
        "tank": 0,
        "heal": 0,
        "push": 2,
        "gank": 4,
        "mobile": 2
    },
    75: {
        "localized_name": "Silencer",
        "id": 75,
        "spell_caster": True,
        "right_clicker": False,
        "support": True,
        "initiate": 1,
        "big_ult": 5,
        "offlane": 2,
        "tank": 0,
        "heal": 0,
        "push": 0,
        "gank": 2,
        "mobile": 0
    },
    76: {
        "localized_name": "Outworld Devourer",
        "id": 76,
        "spell_caster": True,
        "right_clicker": True,
        "support": False,
        "initiate": 0,
        "big_ult": 5,
        "offlane": 0,
        "tank": 0,
        "heal": 0,
        "push": 0,
        "gank": 2,
        "mobile": 0
    },
    77: {
        "localized_name": "Lycan",
        "id": 77,
        "spell_caster": False,
        "right_clicker": True,
        "support": False,
        "initiate": 1,
        "big_ult": 2,
        "offlane": 0,
        "tank": 4,
        "heal": 0,
        "push": 5,
        "gank": 1,
        "mobile": 2
    },
    78: {
        "localized_name": "Brewmaster",
        "id": 78,
        "spell_caster": True,
        "right_clicker": False,
        "support": False,
        "initiate": 5,
        "big_ult": 5,
        "offlane": 1,
        "tank": 1,
        "heal": 0,
        "push": 1,
        "gank": 4,
        "mobile": 0
    },
    79: {
        "localized_name": "Shadow Demon",
        "id": 79,
        "spell_caster": False,
        "right_clicker": False,
        "support": True,
        "initiate": 3,
        "big_ult": 0,
        "offlane": 0,
        "tank": 0,
        "heal": 0,
        "push": 0,
        "gank": 4,
        "mobile": 0
    },
    80: {
        "localized_name": "Lone Druid",
        "id": 80,
        "spell_caster": False,
        "right_clicker": True,
        "support": False,
        "initiate": 1,
        "big_ult": 0,
        "offlane": 5,
        "tank": 5,
        "heal": 0,
        "push": 5,
        "gank": 1,
        "mobile": 1
    },
    81: {
        "localized_name": "Chaos Knight",
        "id": 81,
        "spell_caster": False,
        "right_clicker": True,
        "support": False,
        "initiate": 3,
        "big_ult": 4,
        "offlane": 1,
        "tank": 5,
        "heal": 0,
        "push": 5,
        "gank": 2,
        "mobile": 0
    },
    82: {
        "localized_name": "Meepo",
        "id": 82,
        "spell_caster": False,
        "right_clicker": True,
        "support": False,
        "initiate": 3,
        "big_ult": 0,
        "offlane": 1,
        "tank": 1,
        "heal": 0,
        "push": 4,
        "gank": 3,
        "mobile": 0
    },
    83: {
        "localized_name": "Treant Protector",
        "id": 83,
        "spell_caster": False,
        "right_clicker": False,
        "support": True,
        "initiate": 4,
        "big_ult": 5,
        "offlane": 1,
        "tank": 5,
        "heal": 3,
        "push": 2,
        "gank": 2,
        "mobile": 2
    },
    84: {
        "localized_name": "Ogre Magi",
        "id": 84,
        "spell_caster": True,
        "right_clicker": False,
        "support": True,
        "initiate": 2,
        "big_ult": 0,
        "offlane": 0,
        "tank": 3,
        "heal": 0,
        "push": 2,
        "gank": 3,
        "mobile": 0
    },
    85: {
        "localized_name": "Undying",
        "id": 85,
        "spell_caster": False,
        "right_clicker": False,
        "support": True,
        "initiate": 2,
        "big_ult": 0,
        "offlane": 4,
        "tank": 3,
        "heal": 2,
        "push": 2,
        "gank": 1,
        "mobile": 0
    },
    86: {
        "localized_name": "Rubick",
        "id": 86,
        "spell_caster": True,
        "right_clicker": False,
        "support": True,
        "initiate": 3,
        "big_ult": 1,
        "offlane": 1,
        "tank": 0,
        "heal": 0,
        "push": 1,
        "gank": 4,
        "mobile": 0
    },
    87: {
        "localized_name": "Disruptor",
        "id": 87,
        "spell_caster": False,
        "right_clicker": False,
        "support": True,
        "initiate": 2,
        "big_ult": 5,
        "offlane": 1,
        "tank": 0,
        "heal": 0,
        "push": 0,
        "gank": 3,
        "mobile": 1
    },
    88: {
        "localized_name": "Nyx Assassin",
        "id": 88,
        "spell_caster": False,
        "right_clicker": False,
        "support": True,
        "initiate": 4,
        "big_ult": 1,
        "offlane": 5,
        "tank": 1,
        "heal": 0,
        "push": 0,
        "gank": 5,
        "mobile": 4
    },
    89: {
        "localized_name": "Naga Siren",
        "id": 89,
        "spell_caster": False,
        "right_clicker": True,
        "support": False,
        "initiate": 3,
        "big_ult": 5,
        "offlane": 0,
        "tank": 0,
        "heal": 0,
        "push": 5,
        "gank": 3,
        "mobile": 2
    },
    90: {
        "localized_name": "Keeper of the Light",
        "id": 90,
        "spell_caster": False,
        "right_clicker": False,
        "support": True,
        "initiate": 0,
        "big_ult": 0,
        "offlane": 2,
        "tank": 0,
        "heal": 0,
        "push": 4,
        "gank": 2,
        "mobile": 0
    },
    91: {
        "localized_name": "Io",
        "id": 91,
        "spell_caster": False,
        "right_clicker": False,
        "support": True,
        "initiate": 0,
        "big_ult": 3,
        "offlane": 0,
        "tank": 0,
        "heal": 1,
        "push": 0,
        "gank": 5,
        "mobile": 3
    },
    92: {
        "localized_name": "Visage",
        "id": 92,
        "spell_caster": False,
        "right_clicker": False,
        "support": True,
        "initiate": 0,
        "big_ult": 2,
        "offlane": 1,
        "tank": 1,
        "heal": 0,
        "push": 5,
        "gank": 3,
        "mobile": 0
    },
    93: {
        "localized_name": "Slark",
        "id": 93,
        "spell_caster": False,
        "right_clicker": True,
        "support": False,
        "initiate": 4,
        "big_ult": 2,
        "offlane": 5,
        "tank": 1,
        "heal": 0,
        "push": 1,
        "gank": 5,
        "mobile": 5
    },
    94: {
        "localized_name": "Medusa",
        "id": 94,
        "spell_caster": False,
        "right_clicker": True,
        "support": False,
        "initiate": 2,
        "big_ult": 4,
        "offlane": 0,
        "tank": 4,
        "heal": 0,
        "push": 5,
        "gank": 0,
        "mobile": 0
    },
    95: {
        "localized_name": "Troll Warlord",
        "id": 95,
        "spell_caster": False,
        "right_clicker": True,
        "support": False,
        "initiate": 2,
        "big_ult": 4,
        "offlane": 1,
        "tank": 2,
        "heal": 0,
        "push": 3,
        "gank": 3,
        "mobile": 0
    },
    96: {
        "localized_name": "Centaur Warrunner",
        "id": 96,
        "spell_caster": False,
        "right_clicker": False,
        "support": False,
        "initiate": 5,
        "big_ult": 3,
        "offlane": 5,
        "tank": 5,
        "heal": 0,
        "push": 1,
        "gank": 4,
        "mobile": 1
    },
    97: {
        "localized_name": "Magnus",
        "id": 97,
        "spell_caster": True,
        "right_clicker": False,
        "support": False,
        "initiate": 5,
        "big_ult": 5,
        "offlane": 1,
        "tank": 2,
        "heal": 0,
        "push": 0,
        "gank": 3,
        "mobile": 1
    },
    98: {
        "localized_name": "Timbersaw",
        "id": 98,
        "spell_caster": True,
        "right_clicker": False,
        "support": False,
        "initiate": 3,
        "big_ult": 2,
        "offlane": 5,
        "tank": 4,
        "heal": 0,
        "push": 4,
        "gank": 3,
        "mobile": 3
    },
    99: {
        "localized_name": "Bristleback",
        "id": 99,
        "spell_caster": False,
        "right_clicker": True,
        "support": False,
        "initiate": 1,
        "big_ult": 0,
        "offlane": 5,
        "tank": 5,
        "heal": 0,
        "push": 1,
        "gank": 3,
        "mobile": 1
    },
    100: {
        "localized_name": "Tusk",
        "id": 100,
        "spell_caster": False,
        "right_clicker": False,
        "support": False,
        "initiate": 5,
        "big_ult": 1,
        "offlane": 3,
        "tank": 3,
        "heal": 0,
        "push": 0,
        "gank": 5,
        "mobile": 1
    },
    101: {
        "localized_name": "Skywrath Mage",
        "id": 101,
        "spell_caster": True,
        "right_clicker": False,
        "support": True,
        "initiate": 0,
        "big_ult": 3,
        "offlane": 1,
        "tank": 0,
        "heal": 0,
        "push": 0,
        "gank": 4,
        "mobile": 0
    },
    102: {
        "localized_name": "Abaddon",
        "id": 102,
        "spell_caster": False,
        "right_clicker": True,
        "support": True,
        "initiate": 0,
        "big_ult": 0,
        "offlane": 2,
        "tank": 2,
        "heal": 1,
        "push": 1,
        "gank": 2,
        "mobile": 1
    },
    103: {
        "localized_name": "Elder Titan",
        "id": 103,
        "spell_caster": True,
        "right_clicker": False,
        "support": True,
        "initiate": 3,
        "big_ult": 5,
        "offlane": 4,
        "tank": 3,
        "heal": 0,
        "push": 1,
        "gank": 2,
        "mobile": 0
    },
    104: {
        "localized_name": "Legion Commander",
        "id": 104,
        "spell_caster": False,
        "right_clicker": True,
        "support": False,
        "initiate": 5,
        "big_ult": 3,
        "offlane": 2,
        "tank": 1,
        "heal": 2,
        "push": 0,
        "gank": 5,
        "mobile": 1
    },
    106: {
        "localized_name": "Ember Spirit",
        "id": 106,
        "spell_caster": False,
        "right_clicker": True,
        "support": False,
        "initiate": 3,
        "big_ult": 0,
        "offlane": 0,
        "tank": 0,
        "heal": 0,
        "push": 3,
        "gank": 5,
        "mobile": 3
    },
    107: {
        "localized_name": "Earth Spirit",
        "id": 107,
        "spell_caster": True,
        "right_clicker": False,
        "support": True,
        "initiate": 5,
        "big_ult": 5,
        "offlane": 2,
        "tank": 2,
        "heal": 0,
        "push": 0,
        "gank": 5,
        "mobile": 0
    },
    109: {
        "localized_name": "Terrorblade",
        "id": 109,
        "spell_caster": False,
        "right_clicker": True,
        "support": False,
        "initiate": 0,
        "big_ult": 2,
        "offlane": 0,
        "tank": 0,
        "heal": 0,
        "push": 5,
        "gank": 1,
        "mobile": 0
    },
    110: {
        "localized_name": "Phoenix",
        "id": 110,
        "spell_caster": True,
        "right_clicker": False,
        "support": True,
        "initiate": 1,
        "big_ult": 5,
        "offlane": 5,
        "tank": 1,
        "heal": 1,
        "push": 1,
        "gank": 2,
        "mobile": 2
    },
    111: {
        "localized_name": "Oracle",
        "id": 111,
        "spell_caster": False,
        "right_clicker": False,
        "support": True,
        "initiate": 0,
        "big_ult": 2,
        "offlane": 1,
        "tank": 0,
        "heal": 2,
        "push": 0,
        "gank": 1,
        "mobile": 0
    },
    105: {
        "localized_name": "Techies",
        "id": 105,
        "spell_caster": True,
        "right_clicker": False,
        "support": True,
        "initiate": 0,
        "big_ult": 0,
        "offlane": 2,
        "tank": 0,
        "heal": 0,
        "push": 3,
        "gank": 5,
        "mobile": 0
    },
    112: {
        "localized_name": "Winter Wyvern",
        "id": 112,
        "spell_caster": True,
        "right_clicker": False,
        "support": True,
        "initiate": 5,
        "big_ult": 5,
        "offlane": 2,
        "tank": 0,
        "heal": 3,
        "push": 1,
        "gank": 2,
        "mobile": 1
    },
    113: {
        "localized_name": "Arc Warden",
        "id": 113,
        "spell_caster": False,
        "right_clicker": True,
        "support": False,
        "initiate": 0,
        "big_ult": 1,
        "offlane": 1,
        "tank": 0,
        "heal": 0,
        "push": 5,
        "gank": 2,
        "mobile": 0
    }
}

hero_stat_total = {
        "spell_caster": 0,
        "right_clicker": 0,
        "support": 0,
        "initiate": 0,
        "big_ult": 0,
        "offlane": 0,
        "tank": 0,
        "heal": 0,
        "push": 0,
        "gank": 0,
        "mobile": 0
}

for (id,hero) in hero_stats.iteritems():
    for (key, value) in hero.iteritems():
        if key =="id" or key =='localized_name':
            continue
        if key in ["spell_caster", "right_clicker", "support"] and value:
            hero_stat_total[key]+=1
        else:
            hero_stat_total[key]+= value


